### PR TITLE
Immutable index

### PR DESCRIPTION
**Pull request by aljazerzen**
Fixes the comment from #4592

### CODE REVIEW

**Comment by aljazerzen** [comment]
When approved, I'll add the patch for backporting

**Comment by aljazerzen** [comment]
Wait, should this also apply to `std::_slice`?

**Comment by elprans** [comment]
> Wait, should this also apply to `std::_slice`?

Yes

**Comment by msullivan** [comment]
I tested `_slice` at some point and it seemed fine? Add tests, I guess, but it might not need a change

**Review by msullivan — APPROVED** [review]

**Comment by msullivan** [comment]
Or wait, should we just make raise_on_null immutable?

**Comment by aljazerzen** [comment]
> Or wait, should we just make raise_on_null immutable?

I think we don't:

https://github.com/edgedb/edgedb/blob/immutable-index/edb/pgsql/metaschema.py#L1208-L1215

**Pull request merged**
