### PR TITLE
Start renaming server components

### PR DESCRIPTION
**Pull request by msullivan**
- Update a number of messages we print
- Change some docstrings that were showing up in my search of string
  constants but aren't user facing
- Update user-facing environment variables to also support versions
  with the new name. If both are specified, emit a warning and prefer
  the new one.
- Create new entry point executables for our commands. (Do we need to
  do this a second time in edgedb-pkg?)

My philosophy here is that "edgedb" will remain the "internal
codename" of the product probably forever. Anything that is just
developer facing will retain its current name.

### CODE REVIEW

**Review by aljazerzen — APPROVED** [review]
Don't merge this before we cut the 6.x branch.

**Comment by msullivan** [comment]
I think the plan is that this should be in 6.x

**Comment by 1st1** [comment]
> I think the plan is that this should be in 6.x

Correct

**Comment by MartinCura** [comment]
👀 I'm dying of curiosity of why the rename

**Pull request merged**
