### PR TITLE
repl: add commands \dr list roles, \dm list modules, \dt list types, …

### PR DESCRIPTION
**Pull request by schettino72**
…\d describe type.

### CODE REVIEW

**Comment by schettino72** [comment]
refs #179 

Not sure you already have a design on how commands should look like.
Let me know what you guys think. 
Output should probably be in table format like psql...

**Comment by 1st1** [comment]
I like this.  @elprans your thoughts?

**Comment by elprans** [comment]
I think this is useful.  Perhaps `\d <type>` should produce SDL output, i.e

```
> \d std::Object
type std::Object {
  link __type__ -> schema::Type;
  property id -> std::uuid;
}
```

**Comment by 1st1** [comment]
> I think this is useful. Perhaps \d <type> should produce SDL output, i.e

+1, although it's not that easy to implement, right?  I mean ideally we should list all indexes, all constraints, etc.

**Comment by elprans** [comment]
> although it's not that easy to implement, right

Why not? All of that is introspectable and can be fetched in a single query. But just the links/properties would be good for the initial implementation.

**Comment by schettino72** [comment]
My original idea was to have `\dx` commands to output in tabular text. And have another command to dump the schema (SDL or DDL).

So I agree there should be a way to generate SDL, just concerned about having some consistency in the command interface. But of course you guys decision.

Right now there is no way generate a "schema" dump right?
Does the SDL support Administration statements like "ROLE" ?

If `\d` displays SDL... what should `\dr` should display? how the properties `allow_login`, `is_superuser` should be displayed? (right now it only display role name)

**Comment by elprans** [comment]
> If \d displays SDL... what should \dr should display? how the properties allow_login, is_superuser should be displayed? (right now it only display role name)

I don't think we should be overly concerned with the consistency of `\d` output, and instead find the most useful and readable format for each use case.  Tables make sense for simple schema items, but object types may contain lots of stuff and SDL-ish presentation makes sense to me from the familiarity and readability standpoint.  @1st1 @vpetrovykh what do you guys think?

>  Does the SDL support Administration statements like "ROLE" ?

It doesn't.

> Right now there is no way generate a "schema" dump right?

Not right now, but there will be `edgedb dump` in Alpha 2.

**Comment by 1st1** [comment]
> I don't think we should be overly concerned with the consistency of \d output, and instead find the most useful and readable format for each use case. [...] @1st1 @vpetrovykh what do you guys think?

+1.  There's nothing inherently special about tabular output.  We will use it where it makes sense, but in this case SDL makes more sense from the usability standpoint.

**Comment by vpetrovykh** [comment]
Yeah, the \d commands are convenience shortcuts made for humans, so the output should be whatever is good for readability, they don't have to produce valid SDL.

**Comment by schettino72** [comment]
Ok, got it. I will work on it when i have time.

**Comment by schettino72** [comment]
Finally did some work on this. Still WIP and lots to do...
Just want to check if you guys thing this is an ok approach.
Basically I just created an "SDLRenderer".

I am using the `User` type from `cards` (in test folder sample schema).

```
abstract type Named {
    required property name -> str {
        delegated constraint exclusive;
    }
}

type User extending Named {
    multi link deck -> Card {
        property count -> int64;
    }

    property deck_cost := sum(.deck.cost);

    multi link friends -> User {
        property nickname -> str;
        # how the friend responded to requests for a favor
        #property favor -> array<bool>
    }

    multi link awards -> Award {
        constraint exclusive;
    }
}
```

So far I get the following output:

```
abstract type Named extending Object {
    required property name -> str {
        constraint exclusive;
    }
}

type User extending Named {
    property deck_cost -> int64;
    required property name -> str {
        constraint exclusive;
    }
    multi link awards -> Award {
        constraint exclusive;
    }
    multi link deck -> Card {
        property count -> int64;
    }
    multi link friends -> User {
        property nickname -> str;
    }
}
```

Notes:

- I could not find `delegated` info of `constraint` from introspection
- Also could not figure when a property is defined in a type or in a base type, actually I think it is nice to show properties from base types. But probably should have some kind of indication.
- is possible to get the order in which properties/links were defined?
- other differences I still need to work on

**Comment by elprans** [comment]
> I could not find delegated info of constraint from introspection

This is a bug.  

> Also could not figure when a property is defined in a type or in a base type, actually I think it is nice to show properties from base types. But probably should have some kind of indication.

Yes.  I'm working on a patch to add this kind of tracking to the inherited objects.

> is possible to get the order in which properties/links were defined?

It's undefined.

> other differences I still need to work on 

The approach looks good to me. Thanks!

**Comment by funkyfuture** [comment]
> Yeah, the \d commands are convenience shortcuts made for humans

not really with non-querty keyboard layouts b/c of the `\` with regards to typing. regarding readability, i'd say it's convenient for Postgres users, not all humans.

**Comment by 1st1** [comment]
@elprans do your last two PRs unblock this one?

**Comment by elprans** [comment]
@1st1 Mostly, but we still need to expose the information on whether a particular field was inherited or defined locally in the introspection schema (i.e. the `field_inh_map`).

**Comment by 1st1** [comment]
@elprans can you work on that soon?

@schettino72 Eduardo, are you interested in finishing this PR?  We'd like to get it merged as soon as we can.

**Comment by elprans** [comment]
The other thing to consider here is whether or not do we want make this a proper command, i.e. `DESCRIBE TYPE Foo` as opposed to a CLI feature.

**Comment by 1st1** [comment]
> The other thing to consider here is whether or not do we want make this a proper command, i.e. DESCRIBE TYPE Foo as opposed to a CLI feature.

I'm open to that.  That would make it much easier to implement third party tools/repls.  @victor do you want to spec this in a new issue?

**Comment by schettino72** [comment]
Sorry guys. I had zero time for open-source lately. I am hoping I will have time to get back in a week or two.

**Comment by MrNaif2018** [comment]
@1st1 @elprans I can finish this pr if needed. What should I do?

**Comment by elprans** [comment]
@MrNaif2018 We need to weigh the pros and cons of the two approaches and decide which to pursue:

1) Implement the "list" and the "describe" the way @schettino72 is proposing in this PR: i.e. through introspection queries and client-side rendering.

2) Implement this functionality as server commands, i.e `DESCRIBE TYPE` that simply returns a pre-rendered string representation of the desired schema item.

The second option requires less code duplication and, IMO, better UX (although we could, with some effort, recognize `DESCRIBE` as a client-side command, like we do for slash commands).  On the other hand, the first option does not require adding new syntax, and is more flexible, as it is easier to customize the output rendering (color highlighting, width-formatting etc).

@1st1 @vpetrovykh @ambv what are your thoughts?

**Comment by MrNaif2018** [comment]
My thoughts are for the second option, because the more client libraries the more code repetition. But can't \dr and other commands internally call describe type and have all the color rendering then?

**Comment by MrNaif2018** [comment]
My thoughts are for the second option, because the more client libraries the more code repetition. But can't \dr and other commands internally call describe type and have all the color rendering then?

**Comment by 1st1** [comment]
> Implement this functionality as server commands, i.e DESCRIBE TYPE that simply returns a pre-rendered string representation of the desired schema item.

This, the second option.  Even though we'll need to add some new syntax, that will make it easier for people to write tools / ide plugins / repls / etc for EdgeDB.

**Comment by 1st1** [comment]
@vpetrovykh Let's make this a high priority.

**Comment by vpetrovykh** [comment]
There's a number of changes that impact the implementation of this PR. I'm closing it in favour of the reworked version (PR #853).

**Pull request closed without merging**
