### PR TITLE
Include auth_ext static assets in the package build

### PR DESCRIPTION
**Pull request by msullivan**
I verified that the assets are in the sdist.

Also add a test that fetches one of the assets. I'll kick off a
release dry-run to verify that it works.

### CODE REVIEW

**Review by scotttrinh — APPROVED** [review]
Cool! Test makes sense to me, but does that really test that it is packaged?

**Comment by elprans** [comment]
> Cool! Test makes sense to me, but does that really test that it is packaged?

Tests run on production packages, so yes.

**Comment by msullivan** [comment]
> > Cool! Test makes sense to me, but does that really test that it is packaged?
> 
> Tests run on production packages, so yes.

To clarify, release/nightly/dry-run build tests run on production packages, and I kicked off a dry-run to test this, which looks good (all the failed tests are parser related and will be fixed by https://github.com/edgedb/edgedb/pull/6375): https://github.com/edgedb/edgedb/actions/runs/6672556465/job/18137460047

Running tests locally (and I think in CI) use the dev build.

**Comment by scotttrinh** [comment]
Ahh, that was the piece I was missing to tie together the dry run and this test 🙌

**Pull request merged**
