### PR TITLE
Fix RECURSIVE over SQL adapter

### PR DESCRIPTION
**Pull request by aljazerzen**

### CODE REVIEW

**Review by msullivan — APPROVED** [review]

**Comment by msullivan** [comment]
How does using it multiple times work?

**Comment by aljazerzen** [comment]
In SQL, recursive keyword does not apply to a specific CTE, but it applies to the whole query. So any/all CTEs can be recursive when the keyword is present.

Location of the flag in our AST is the questionable part here. We should probably has a separate ast node `With { ctes: List[CommonTableExpression], recursive: bool }`.

**Comment by aljazerzen** [comment]
(... but my code does not take that into account properly)

**Comment by msullivan** [comment]
Remember to label for backport. too

**Pull request merged**
