### PR TITLE
Add a 'future' system and a 'nonrecursive_policies' future

### PR DESCRIPTION
**Pull request by msullivan**
A 'feature' is a configuration flag that lives inside the database
itself, and can control major questions of language behavior that can
impact compilation (for example, nonrecursive_policies affects the
compilation of access policies in a way that can affect function
bodies). Features are explicitly built in to the language, and are set
up so that they can trigger other schema changes when they are
toggled.

The syntax is basically the same as for extensions. (The core
difference between features and extensions is that extensions ought to
be self-contained and not change the meaning of language features!)

The intent is to use features somewhat like python's
"from __future__ import ...".

Then, implement a 'nonrecursive_policies' feature.  This feature flag
disables the evaluation of policies within policies themselves. This
is probably what the default behavior should have been, and it is
important to provide this behavior ASAP, but it would be unreasonable
to unconditionally change the behavior in a point release.
See #4564 for one place where the current behavior has made a use-case
impossible.

I'd be thrilled if someone had a better name than nonrecursive_policies.

We will be able to cherry-pick this to 2.x using #4573.

### CODE REVIEW

**Comment by 1st1** [comment]
Please wait for my review

**Review by elprans — COMMENTED** [review]
Implementation looks good to me, though we probably still want to bikeshed on the name a bit, e.g. it was suggested that we may want to use `future` or `future feature` to stress that this mechanism is intended for smooth deprecation of schema features (or bugs) and not another sort of extension-like or config-like mechanism.

**Comment by 1st1** [comment]
The PR looks good but I'd like to bikeshed about naming. I don't like `using feature xxx` because "feature" implies some kind of permanent knob. But we do want to drop these "features" eventually. Hence I'm -1 on having the "using feature" naming.

I like `using future nonrecursive_policies` or `using future simple_policies` more. The syntax suggests that it flips some behavior to what it will be in the future.

**Comment by zackelan** [comment]
shim? [well-established term](https://en.wikipedia.org/wiki/Shim_(computing)) that I think has the connotations we want

and I like "simple" or "basic" policies over nonrecursive. maybe "extended" instead of recursive?

**Review by elprans — APPROVED** [review]

**Pull request merged**
