### PR TITLE
Build musl versions of server

### PR DESCRIPTION
**Pull request by elprans**
Fixes: #4253

### CODE REVIEW

**Review by fantix — APPROVED** [review]

**Comment by tailhook** [comment]
I'm not sure what this means. Is this a statically-linked musl build? Or does it require musl libc to be present on the system? Does it work on Alpine?

Will we have any issues with the musl build because of smaller default C stack? Will it fit standard python's recursive depth limit? Does postgres work well on such a small stack, or does it have a mechanism to adjust the stack size?

**Comment by elprans** [comment]
> I'm not sure what this means. Is this a statically-linked musl build? 

Dynamically linked.

> Does it work on Alpine?

Yes, I also tested Void Linux and a `FROM scratch` container with a custom-built musl.

> Will it fit standard python's recursive depth limit? Does postgres work well on such a small stack, or does it have a mechanism to adjust the stack size?

Well, alpine is a fairly popular base image for Python, I've not seen anybody complain about it.  Postgres is also packaged by Alpine without any specific hacks, AFAIK stack size isn't hardcoded and queried via `RLIMIT_STACK` or a similar technique.  FWIW, the test suite passes just fine.

**Comment by tailhook** [comment]
> AFAIK stack size isn't hardcoded and queried via `RLIMIT_STACK` or a similar technique.

Here is the quote from musl documentation:

> The default stack size for new threads on glibc is determined based on the resource limit governing the main thread’s stack (RLIMIT_STACK). It generally ends up being 2-10 MB.
>
> musl provides a default thread stack size of 128k (80k prior to 1.1.21).

Note: for other threads than main, you can change the stack size on thread creation. But as far as I know there is no such method for main thread with musl libc.

On the other hand:
> Since 1.1.21, musl supports increasing the default thread stack size via the PT_GNU_STACK program header, which can be set at link time via -Wl,-z,stack-size=N.

So this is a compile-time flag.

> Well, alpine is a fairly popular base image for Python, I've not seen anybody complain about it

It looks like Python build in Alpine is specially tweaked to account that:
* https://github.com/python/cpython/issues/76488#issuecomment-1093770247
* https://git.alpinelinux.org/aports/tree/main/python3/APKBUILD?h=3.16-stable#n119

So it looks like it isn't autodetected. Since you aren't using Alpine's package, can you make sure that this flag is set?

For postgres, I can't find anything relevant in Alpine package, so maybe it does some magic internally, or maybe nobody uses postgres Alpine package for anything serious. Hard to say.

**Comment by elprans** [comment]
> So it looks like it isn't autodetected. Since you aren't using Alpine's package, can you make sure that this flag is set?

Sure.  FWIW, Python 3.11 no longer uses the C stack for Python calls, so this wouldn't be an issue once we switch.

**Comment by notramo** [comment]
> For postgres, I can't find anything relevant in Alpine package, so maybe it does some magic internally, or maybe nobody uses postgres Alpine package for anything serious. Hard to say.

The Postgres official Docker images provide two versions: Debian Bullseye, and Alpine.
So I guess Postgres works well on Alpine if the upstream devs ship it.

**Pull request merged**
