### PR TITLE
Split Build and Test phases into separate jobs

### LINKED ISSUE #1454: Split the package build-and-test workflow job into two jobs: build and test.
Currently, package build and built package tests are done as steps of the same job.  Unfortunately, it seems like Github Actions have an (undocumented) job run time limit on macOS of 60 minutes (the documentation claims that the limit is 6 hours).  It might be a fluke or a temporary bug.  Regardless, separating build and test into separate jobs seems like a cleaner arrangement anyway.

### PR DESCRIPTION
**Pull request by ambv**
Fixes #1454

### CODE REVIEW

**Comment by elprans** [comment]
You didn't seem to have updated the actual workflow files.

**Comment by ambv** [comment]
jon-stewart-really

**Comment by elprans** [comment]
What about the release flow? Or do you want to test this on the nightly first?

**Comment by ambv** [comment]
> Or do you want to test this on the nightly first?

Yes. It feels wrong to make changes to the release flow that I won't be testing now. If I got hit by a bus and the nightlies turned out to be borked, the old release flow will still work.

As soon as the nightly is green I will copy the changes to the main release workflow.

**Pull request merged**
