### PR TITLE
Stop using catalog version for the default tenant id

### PR DESCRIPTION
**Pull request by msullivan**
I don't think it ever is really helpful, except maybe in some dev
situations where we don't actually use it.

Anybody relying on tenant ids almost certainly needs to be specifying
them explicitly to get anything to work.

Just use `'E`' as the tenant id. This will give us nice predictible
database names and eases inplace upgrades.

### CODE REVIEW

**Comment by elprans** [comment]
> I don't think it ever is really helpful, except maybe in some dev
> situations where we don't actually use it.

Wouldn't this essentially render `--ignore-other-tenants` broken?

**Comment by msullivan** [comment]
> > I don't think it ever is really helpful, except maybe in some dev
> > situations where we don't actually use it.
> 
> Wouldn't this essentially render `--ignore-other-tenants` broken?

It breaks the use case of running different versions of `edgedb` against the same backend without specifying tenant names. That's a pretty marginal use case, and if anybody cares about it they can explicitly specify a tenant name, right?

**Comment by msullivan** [comment]
Plus, the flag is mostly undocumented

**Comment by elprans** [comment]
> Plus, the flag is mostly undocumented

Fair enough, but please do remember to document this in the upgrade considerations of the 6.0 changelog.

**Review by elprans — APPROVED** [review]

**Pull request merged**
