### PR TITLE
Fix non-transactional errors in Postgres 14.7

### PR DESCRIPTION
**Pull request by fantix**
Cherry-pick #5026 without bumping Postgres to 14.7

### CODE REVIEW

**Comment by elprans** [comment]
Why not just bump 2.x to 14.7?

**Comment by fantix** [comment]
I'm ok to bump - it wasn't up to date with the master (14.4 comparing to 14.6) so I thought it was kept back for a reason.

**Comment by msullivan** [comment]
Are we OK bumping the actual release of 2.x to 14.7?
(I'd prefer to keep the dev version synced with the release version, though it doesn't really matter)

**Comment by elprans** [comment]
> Are we OK bumping the actual release of 2.x to 14.7?

Yes. I'll do that.  No reason not to bump to the latest bugfix release.

**Comment by msullivan** [comment]
Roger, sounds good

**Pull request merged**
