### PR TITLE
Add a __std__ alias for 'std'; fix constant extraction

### PR DESCRIPTION
**Pull request by 1st1**
Add a '__std__' alias for the 'std' module.

This fixes constant extraction in queries wit a
'WITH std AS MODULE ...' clause.

Issue #1457.

### CODE REVIEW

**Comment by 1st1** [comment]
> There are a bunch of hardcoded references to std:: in edb.edgeql.compiler, we must update them also.

Most of them just resolve some type in std and that's unrelated to modaliases. The only cases I found where `std::` names are actually injected into the IR are:

* serialization of EdgeQL types to IR; if std is shadowed, we should compile `int64` to `__std__::int64`

* complex array casts, where we inject `std::array_agg` and other functions.

I've fixed both issues and added tests for them.

**Comment by elprans** [comment]
> Most of them just resolve some type in std and that's unrelated to modaliases. 

Modaliases affect `schema.get()`, so those references might get affected also.

**Comment by 1st1** [comment]
> Modaliases affect schema.get(), so those references might get affected also.

You use `get_track_schema_type` and `get_track_schema_object` helpers in most places that don't pass `ctx.modaliases` to `schema.get`

**Comment by 1st1** [comment]
Basically I've updated all places where `ctx.env.modaliases` are used with `std::` names.

**Pull request merged**
