### PR TITLE
Fix Insert (Alternative Method)

### PR DESCRIPTION
**Pull request by zchenb**
Changed inserts to take a single object reference.

### CODE REVIEW

**Comment by zchenb** [comment]
I prefer the method of #4920, but the modified grammar will cause test failures. This is a workaround.

**Review by msullivan — APPROVED** [review]
This looks good!

What do you prefer about the other version? (Using `AtomicExpr` doesn't seem like the right thing)

**Comment by zchenb** [comment]
This version may be better if AtomicExpr is not the right thing. Shall I go ahead and merge?

**Comment by msullivan** [comment]
Go for it

**Pull request merged**
