### PR TITLE
Add array index number to output when casting from json to array.

### PR DESCRIPTION
**Pull request by dnwpark**
Given the query `SELECT <array<int64>>to_json('[1, 2, "asdf"]')`, produces the error:
```
InvalidValueError: while casting 'std::json' to 'array<std::int64>', in array elements, at index 2, expected JSON number or null; got JSON string
```

### CODE REVIEW

**Comment by dnwpark** [comment]
Adding `error_message_context` in `fini_expression` is super dubious imo

**Comment by msullivan** [comment]
> Adding `error_message_context` in `fini_expression` is super dubious imo

Why is that necessary?

**Comment by dnwpark** [comment]
In `_compile_call_args` there is a check to ensure that all args have a known multiplicity. The multiplicity is added in `fini_expression`. I suppose the other alternative is to add an override to `infer_multiplicity` on `TypeCast`.

**Comment by msullivan** [comment]
Yeah, adding it to multiplicity and cardinality checks is the correct thing

**Comment by dnwpark** [comment]
Benchmarking against three queries:

**Simple null** - 10000 times
```
client.query(
    "SELECT <array<int64>>to_json(<str>$input)",
    input='[null]'
)
```
- `master`: `8.927s`
- With array indexes: `13.453s`

**Long array** - 1000 times
```
client.query(
    "SELECT <array<int64>>to_json(<str>$input)",
    input='['+','.join(str(i) for i in range(1000))+',null'+']'
)
```
- `master`: `4.647s`
- With array indexes: `10.134s`

**Long and deep array** - 1000 times
```
client.query(
    "SELECT <array<tuple<array<tuple<array<int64>>>>>>to_json(<str>$input)",
    input='['+','.join('[[[[1,2,3],[4,5,6],[7,8,9]]]]' for i in range(1000))+',[[[[1,2,null]]]]'+']'
)
```
- `master`: `9.406s`
- With array indexes: `90.841s`

**Comment by dnwpark** [comment]
@msullivan non-trivial cases seem convincingly much slower.

**Comment by msullivan** [comment]
Great work experimenting with this, though!

**Comment by msullivan** [comment]
Also, we support `json` arguments directly too

**Pull request closed without merging**
