### PR TITLE
Add remove data directory command

### LINKED ISSUE #5075: Add `rm-data-dir` command to `edb`
The option should remove the default data directory in the case of version conflict.

### PR DESCRIPTION
**Pull request by zchenb**
Fixes #5075

### CODE REVIEW

**Comment by msullivan** [comment]
I think the idea was to add it to the `edb` dev helper commands, not to the real server. `edb/tools/edb.py` would be where to look

**Comment by zchenb** [comment]
Do you mean that I should add it as a command, so I could run `edb rm-data-dir`?

**Comment by zchenb** [comment]
It should be a command. Confirmed in Slack.

**Comment by zchenb** [comment]
Fixed. Please take another look!

**Review by 1st1 — APPROVED** [review]

**Pull request merged**
