### PR TITLE
Fix tenant shutdown in multi-tenant mode

### PR DESCRIPTION
**Pull request by fantix**
1. Request frontend connections to stop
2. Add a timeout to interrupt if they don't stop in time

### CODE REVIEW

**Review by nsidnev — APPROVED** [review]

**Comment by elprans** [comment]
How does this interact with the `offline` readiness state?

**Comment by fantix** [comment]
> How does this interact with the `offline` readiness state?

It's not currently reporting `offline` during the removal of a tenant, expecting the controlling plane to set `offline` in advance. However, I think it makes sense to report `offline` regardless of the value in the `readiness-state-file`, as soon as a tenant is removed from the `multitenant-config-file`.

**Comment by elprans** [comment]
What I meant is that we set tenant state to `offline` already and that should effectively terminate all connections (possibly after a timeout).  This change is still valid, but toggling the readiness state should have a similar effect.

**Comment by fantix** [comment]
> What I meant is that we set tenant state to `offline` already and that should effectively terminate all connections (possibly after a timeout). This change is still valid, but toggling the readiness state should have a similar effect.

Sounds reasonable! Will create a new PR for that - it'll involve some complexity of shutdown task management (which should be cancelled in case the state is switched back to online before timeout).

**Pull request merged**
