### PR TITLE
4.3 cherry picks

### PR DESCRIPTION
**Pull request by fantix**
* #6531 
* #6562 
* #6588

### CODE REVIEW

**Comment by aljazerzen** [comment]
Hmm, I'll move these commits to the releases branch one by one, so they don't get squashed and we don't get a merge commit.

**Comment by fantix** [comment]
I can do "rebase and merge" instead of "squash and merge" on this PR, which does the same thing I think

**Comment by aljazerzen** [comment]
I think "rebase and merge" will still produce a merge commit:

```
A --------------------- Merge
 \__ CP1 __ CP2 __ CP3 __/
```

Since releases/4.x cannot be forcepushed to, I'd prefer not to rick non-linear history.

**Comment by msullivan** [comment]
> I think "rebase and merge" will still produce a merge commit:
> 
> ```
> A --------------------- Merge
>  \__ CP1 __ CP2 __ CP3 __/
> ```
> 
> Since releases/4.x cannot be forcepushed to, I'd prefer not to rick non-linear history.

Rebase and merge doesn't produce a merge commit, it does a rebase. "Create a merge commit" will do a merge.

... I've pretty sure I've force pushed to release branches, but we should at least try not to

**Comment by aljazerzen** [comment]
Oh, ok I see that I'm mistaken.

But yeah, I've force-pushed to release too, but I think Elvis disabled that because I was too liberal with it :dagger:

**Pull request closed without merging**
