### PR TITLE
Swap the default behavior of sorting by emptys sets

### PR DESCRIPTION
**Pull request by msullivan**
That is, make `EMPTY LAST` the default for `ASC` and `EMPTY FIRST` the
default for `DESC`. This seems like worse behavior, but it is pretty
marginal, and it is what SQL can do quickly.

It turns out we had zero tests for this behavior.

Partial fix to #3234.

### CODE REVIEW

**Review by elprans — APPROVED** [review]

**Comment by vpetrovykh** [comment]
> This seems like worse behavior, but it is pretty
> marginal, and it is what SQL can do quickly.

I suppose that this is a marginal enough case (because it can be trivially overridden) that the fact that `{}` is fairly reasonable interpretation of "smallest" for the purpose of ordering can be overlooked, but is it *really* that big of a performance boost?

**Comment by msullivan** [comment]
2ms vs 60ms, on a test doing 
`SELECT Block { hash, height } ORDER BY .height ASC EMPTY LAST LIMIT 50`
vs
`SELECT Block { hash, height } ORDER BY .height ASC EMPTY FIRST LIMIT 50`, respectively, on a table with a million rows.

(And, also with a pending PR of mine that tries to avoid putting the body of ORDER BY in a subquery.)

**Comment by vpetrovykh** [comment]
Wow! OK, faster default it is then.

**Comment by msullivan** [comment]
Oh, wait! We should not do this!

Postgres lets you specify where to put NULLS in an index! We should do that instead.

**Pull request closed without merging**
