### PR TITLE
edb.test: Make it possible to specify the output format explicitly

### PR DESCRIPTION
**Pull request by elprans**
The new `--output-format` option allows choosing from the following:

* 'auto' -- auto-detect the output format (current behavior, default)
* 'simple' -- simple terse output
* 'stacked' -- group output by the test suite
* 'verbose' -- echo each test result on a separate line.

### CODE REVIEW

**Comment by 1st1** [comment]
We already have the `-v` flag that clashes (or just the same?) with the proposed `--output-format=verbose`.

**Comment by elprans** [comment]
You will have extra verbosity around test collection and bootstrap, test progress will use the `MultilineRenderer`.

**Comment by 1st1** [comment]
But MultilineRenderer can break with extra verbosity, it relies on tests being run quiet.

**Comment by 1st1** [comment]
Just raise an error if verbose mode is on and MultilineRenderer is selected.

**Comment by elprans** [comment]
Alright, I added a check.

**Pull request merged**
