### PR TITLE
Add args to the server for automatic temp cluster bootstrap

### PR DESCRIPTION
**Pull request by 1st1**
This adds the following args to the edgedb server:

* --temp-dir - to pick a random temp dir for the db cluster
* --auto-shutdown - to shutdown automatically when last connection
  disconnects
* --echo-runtime-info - to echo JSON with runtime parameters
  (runstate dir & the port the server listens on)

### CODE REVIEW

**Comment by 1st1** [comment]
Ready for review but don't merge yet; I'm about to start experimenting with jest.

**Comment by 1st1** [comment]
Interestingly, the new test used to fail on Python 3.7 consistently and works flawlessly on 3.8. 🤷‍♂️

**Comment by elprans** [comment]
Do you want to enable mypy properly on these modules?  You seem to have added a bunch of type annotations.

**Comment by 1st1** [comment]
> Do you want to enable mypy properly on these modules? You seem to have added a bunch of type annotations.

Not right now.

**Pull request merged**
