### PR TITLE
Tiny fix of DESCRIBE CURRENT MIGRATION

### PR DESCRIPTION
**Pull request by tailhook**
Current master fails on empty `proposed` list.

### CODE REVIEW

**Comment by elprans** [comment]
The current coding is intentional: it sends only the first statement of each proposed scenario instead of the whole script.  Clarification: current implementation does not yet support variants properly.

**Comment by tailhook** [comment]
> The current coding is intentional: it sends only the first statement of each proposed scenario instead of the whole script. Clarification: current implementation does not yet support variants properly.

Hm. Okay. But this should be fixed anyway:
```
Error: ERROR: InternalServerError: tuple index out of range
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "/work/edb/server/procpool/worker.py", line 75, in worker
          res = await meth(*args)
        File "/work/edb/server/compiler/compiler.py", line 1712, in compile_eql_tokens_in_tx
          return self._compile(ctx=ctx, tokens=eql_tokens)
        File "/work/edb/server/compiler/compiler.py", line 1327, in _compile
          comp: dbstate.BaseQuery = self._compile_dispatch_ql(ctx, stmt)
        File "/work/edb/server/compiler/compiler.py", line 1250, in _compile_dispatch_ql
          return self._compile_ql_migration(ctx, ql)
        File "/work/edb/server/compiler/compiler.py", line 885, in _compile_ql_migration
          'text': proposed[0],
      IndexError: tuple index out of range
```

**Comment by elprans** [comment]
> But this should be fixed anyway:

Ah, yes, of course.

**Comment by elprans** [comment]
The `IndexError` here was fixed some time ago.

**Pull request closed without merging**
