### PR TITLE
Update the pygments grammar.

### PR DESCRIPTION
**Pull request by vpetrovykh**
Bring the pygments grammar up-to-date with the current keywords.

This affects the current REPL keyword highlighting.

### CODE REVIEW

**Comment by 1st1** [comment]
Maybe we should make this a separate package? @elprans

**Comment by vpetrovykh** [comment]
I think that we use this in REPL and defining sphinx domains in docs, so since both of those are part of this repo it would be rather unintuitive to factor out the pygments package.

**Comment by elprans** [comment]
There's value of making it a separate package: third-party projects.  It's useful to be able to highlight EdgeQL in Sphinx-generated docs.

**Comment by vpetrovykh** [comment]
So I guess we need an issue for this:
> There's value of making it a separate package: third-party projects. It's useful to be able to highlight EdgeQL in Sphinx-generated docs.

**Pull request merged**
