### PR TITLE
Fixes transactional tests after `execute` disables transactional statements

### PR DESCRIPTION
**Pull request by tailhook**

### CODE REVIEW

**Comment by tailhook** [comment]
@elprans, this does seem like a bug: https://github.com/edgedb/edgedb/pull/2238/commits/d6e60dc3f351b7f391452fb0e6edd9308be8ea6f Please take a look.

**Comment by elprans** [comment]
> this does seem like a bug

What error are you seeing?  The test passes for me (and it passed in CI too).

**Review by elprans — APPROVED** [review]

**Comment by tailhook** [comment]
This is for me:
```
   stmt.result = compile_result_clause(
  File "/work/edb/edgeql/compiler/stmt.py", line 1231, in compile_result_clause
    dispatch.compile(result_expr, ctx=sctx), ctx=sctx)
  File "/usr/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/work/edb/edgeql/compiler/func.py", line 80, in compile_FunctionCall
    funcs = env.schema.get_functions(funcname, module_aliases=ctx.modaliases)
  File "/work/edb/schema/schema.py", line 1694, in get_functions
    return self._base_schema.get_functions(
  File "/work/edb/schema/schema.py", line 1044, in get_functions
    return self._raise_bad_reference(
  File "/work/edb/schema/schema.py", line 1362, in _raise_bad_reference
    raise errors.InvalidReferenceError(
edb.errors.InvalidReferenceError: function 'f1::min' does not exist

Test Traceback:
Traceback (most recent call last):
  File "/work/edb/testbase/server.py", line 128, in wrapper
    self.loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/work/tests/test_server_proto.py", line 1665, in test_server_proto_tx_13
    await test_funcs(working=['f1'],
  File "/work/tests/test_server_proto.py", line 1604, in test_funcs
    await self.con.query(f'SELECT {ns}::min({{1}})'),
  File "/usr/local/lib/python3.9/dist-packages/edgedb/asyncio_con.py", line 293, in query
    result, _ = await self._impl._protocol.execute_anonymous(
  File "edgedb/protocol/protocol.pyx", line 606, in execute_anonymous
  File "edgedb/protocol/protocol.pyx", line 277, in _parse
edgedb.errors.InvalidReferenceError: function 'f1::min' does not exist
```
Maybe it depends on the order of tests :(

**Comment by tailhook** [comment]
Probably some local issue.

**Comment by tailhook** [comment]
Hm, or not. I'm running against this branch: https://github.com/edgedb/edgedb-python/pull/159 This might explain difference (although I don't understand why).

**Comment by elprans** [comment]
OK, I can reproduce locally too. Looking.

**Pull request merged**
