### PR TITLE
graphql: Fix an inheritance bug.

### PR DESCRIPTION
**Pull request by vpetrovykh**
Inheriting a link and changing its target type caused an error in
GraphQL.

GraphQL inheritance does not allow changing the field type, so when
reflecting pointers we must use the top-most base pointer version. It is
possible to access the additional fields (if any) of the subclassed
target type if the subtype is references by name:

```
query {
    Foo {
        bar {
            common
            ... on Bar2 {
                bar2_prop
            }
        }
    }
}
```

Closes: #709.

### CODE REVIEW

**Comment by elprans** [comment]
> GraphQL inheritance does not allow changing the field type

Is this per the spec, or are we papering over graphql-core's behavior?

**Comment by vpetrovykh** [comment]
> > GraphQL inheritance does not allow changing the field type
> 
> Is this per the spec, or are we papering over graphql-core's behavior?

The spec is a bit vague:
https://graphql.github.io/graphql-spec/June2018/#sec-Objects
https://graphql.github.io/graphql-spec/June2018/#sec-Interfaces

The spec doesn't address the specific case of inheritance like this, but it forbids to have "different" fields with the same name and it *requires* the object to have *all* the fields of its interfaces. This would seem like a contradiction in case of implementing 2 interfaces with a field of the same name and related type.

Strictly speaking, the object *is* allowed to implement a field of the same name as the interface and of a sub-type of the interface type, so under this reading it can be argued that this should be legal, whether this was intended and there are any actual GraphQL implementations that do this is another question. So maybe this should be allowed once I reimplement the GraphQL validation.

**Comment by elprans** [comment]
This also doesn't seem to solve the nested view case.

```
CREATE VIEW FooView := (SELECT Foo { bar: { baz := '1' } })
```

```
            query {
                FooView {
                    bar {
                        baz
                    }
                }
            }
```

Having to explicitly specify the derived type of the nested view in the query seems barely usable.

**Comment by vpetrovykh** [comment]
Views are a bit tricky in any case as they kinda generate their own types (maybe that's what the GraphQL "extended" types are for, but I'm still a bit unsure about it), since they basically introduce new fields. On the other hand we should be able to treat them as their own types fairly consistently since we happen to know at compile time whether something is a view or not.

**Comment by vpetrovykh** [comment]
A more practical concern is whether other tools will work with our interpretation of the spec w.r.t. covariant object types for field targets. E.g. will GraphiQL interpret the schema correctly and have all the right auto-completion?

**Pull request merged**
