### PR TITLE
Update createdb.rst

### PR DESCRIPTION
**Pull request by cosmophile**
SDL commit missing final COMMIT command.

### CODE REVIEW

**Comment by elprans** [comment]
Hi @cosmophile!  We have changed how migrations work, and in a4+ they no longer require an explicit transaction block, because `START MIGRATION` and `COMMIT MIGRATION` form a transaction block implicitly now.  The sentence preceding the example you've modified should actually be removed, but the example itself is correct.

**Comment by cosmophile** [comment]
Okay I see! Then I will open an edgedb-js issue, because the following did not work for me to commit a schema to a new database (I'm basically testing a js-only workflow for my db): 

```
    await conn.execute('START TRANSACTION')
    await conn.execute(`START MIGRATION TO {${schema}}`);
    await conn.execute('POPULATE MIGRATION')
    await conn.execute('COMMIT MIGRATION')
```

Whereas the following worked:
```
    await conn.execute('START TRANSACTION')
    await conn.execute(`START MIGRATION TO {${schema}}`);
    await conn.execute('POPULATE MIGRATION')
    await conn.execute('COMMIT MIGRATION')
    await conn.execute('COMMIT')
```

**Comment by elprans** [comment]
@cosmophile It didn't work because you started a transaction and didn't commit it.  Remove `START TRANSACTION` and it'll work.

**Comment by cosmophile** [comment]
Doh.

**Pull request closed without merging**
