### PR TITLE
Test a3 dumps; drop pure-Python dump/restore tooling

### PR DESCRIPTION
**Pull request by 1st1**

### CODE REVIEW

**Comment by ambv** [comment]
Is this part of some issue? I missed when this was decided.

**Comment by 1st1** [comment]
> I missed when this was decided.

When what was decided?

**Comment by ambv** [comment]
To remove the Python dump/restore.

**Comment by 1st1** [comment]
> To remove the Python dump/restore.

Ah, right. Is this a controversial decision? We have the tooling implemented in Rust and by default that is what you get via the `edgedb` command. Invoking the pure-Python dump/restore via `edgedb-old` (I think) isn't practical nor there are use cases for that. The Python dump/restore implementation isn't even maintained anymore, and testing it adds like 15-20 seconds to the overall `edb test` time.

So at this point, I think we should drop it. And we also should drop pure Python repl, but I'll wait until @elprans no longer needs it.

**Comment by ambv** [comment]
It's not controversial, I mostly thought this was part of the Python CLI removal which I missed. I sometimes still use it myself, too, because I can pdb into it.

**Comment by 1st1** [comment]
> Python CLI removal which I missed

Well, ultimately, maintaining two CLIs would be hard for us. So we'll have to have just one.

> I sometimes still use it myself, too, because I can pdb into it.

Maybe we should make Rust CLI more debuggable? What are the actual use cases?

**Comment by ambv** [comment]
> What are the actual use cases?

For me it's a poor man's wireshark ;-) Helped me understand what is going on with connections and the protocol.

**Comment by elprans** [comment]
> For me it's a poor man's wireshark ;-) Helped me understand what is going on with connections and the protocol.

Python CLI uses edgedb-python, there's nothing there that can't be reproduced in a Python REPL with `connection.fetch`

**Pull request merged**
