### PR TITLE
server: add missing args env vars

### PR DESCRIPTION
**Pull request by fantix**
This is somehow missing and mismatching the documentation.

Closes #5364

### CODE REVIEW

**Comment by jackfischer** [comment]
Possible to add `EDGEDB_DEBUG_EDGEQL_TEXT_IN_SQL`?

**Comment by fantix** [comment]
> Possible to add `EDGEDB_DEBUG_EDGEQL_TEXT_IN_SQL`?

Oh all the `EDGEDB_DEBUG_*` [debug switches](https://github.com/edgedb/edgedb/blob/e1f5c1a6bc94677fad43fa3a8657b7b9fa86c57d/edb/common/debug.py#L264) are always supported; they don't need an extra option in the server command parameter list.

**Comment by jackfischer** [comment]
I'm actually getting `/usr/lib/x86_64-linux-gnu/edgedb-server-4/lib/python3.11/site-packages/edb/common/debug.py:259: UserWarning: Unknown debug flag: 'EDGEDB_DEBUG_EDGEQL_TEXT_IN_SQL'` but this may be because we are on 4.7

**Comment by fantix** [comment]
> this may be because we are on 4.7

Right, this option is only added since [5.0](https://github.com/edgedb/edgedb/blob/v5.0/edb/common/debug.py#L146)

**Review by msullivan — APPROVED** [review]

**Pull request merged**
