### PR TITLE
Fix missing pg_config_path in nightly

### PR DESCRIPTION
**Pull request by fantix**

### CODE REVIEW

**Review by elprans — APPROVED** [review]

**Review by elprans — COMMENTED** [review]
> To use openssl from Homebrew on macOS, run:

Perhaps we should automate this in `setup.py` instead of forcing the developer to jump through hoops?

**Comment by fantix** [comment]
Yeah sure, let me try detecting homebrew and openssl installation, or overrides.

**Comment by elprans** [comment]
I would also try `pkg-config --libs --cflags openssl` to support those who use MacPorts.

**Comment by fantix** [comment]
Detection on macOS will be added in a separate PR.

**Pull request merged**
