### PR TITLE
Upgrade rust to 1.45

### PR DESCRIPTION
**Pull request by tailhook**
Needed for: https://github.com/edgedb/edgedb-cli/pull/102

### CODE REVIEW

**Comment by tailhook** [comment]
Do we need to update it somewhere in the build infrastructure?

**Comment by elprans** [comment]
> Do we need to update it somewhere in the build infrastructure?

Yes, [here](https://github.com/edgedb/edgedb-pkg/blob/master/integration/linux/build/update.sh#L65)

**Comment by elprans** [comment]
Also, we probably want to use `https://github.com/actions-rs/toolchain` explicitly and not rely on the toolchain installed in the actions image.

**Comment by tailhook** [comment]
> Also, we probably want to use `https://github.com/actions-rs/toolchain` explicitly and not rely on the toolchain installed in the actions image.

Oh. Didn't know we rely on that :(

**Pull request merged**
