### PR TITLE
Make the 'edb' command run REPL when no subcommand is provided

### PR DESCRIPTION
**Pull request by 1st1**

### CODE REVIEW

**Review by elprans — COMMENTED** [review]
Maybe `edb repl` to make this explicit?

**Comment by 1st1** [comment]
I'm OK with `edb repl`. I'll ask on Slack what others think.

**Comment by 1st1** [comment]
@elprans I've rewritten the PR to have `edb repl` command. Since it actually grants access to the entire `edgedb *` set of commands, should we call it `edb cli`?

**Comment by elprans** [comment]
Sure, `edb cli` works.

**Comment by 1st1** [comment]
Alright, please approve the PR, I'll push an update in a bit

**Review by elprans — APPROVED** [review]

**Pull request merged**
