### PR TITLE
Load `net` module and fix issues

### PR DESCRIPTION
**Pull request by scotttrinh**
In #7676, we were not actually loading the `net.edgeql` module. Once we began loading it, we discovered many issues with syntax and DDL ordering which are fixed here.

### CODE REVIEW

**Review by fantix — APPROVED** [review]
aha, right

**Comment by aljazerzen** [comment]
@scotttrinh I've added a fix, it was an easy one. The two new modules & their types were showing up in SQL introspection (`SELECT * FROM information_schema.tables`), so `pg_dump` tried to create those tables and schemas, but failed for a reason unknown to me.

**Comment by scotttrinh** [comment]
@aljazerzen 

Don't we want these tables to be present in a dump?

**Comment by aljazerzen** [comment]
No, we don't. Accessing EdgeDB via SQL is not meant to expose "internal" or EdgeDB-specific mechanisms. That's because when using `pg_dump` (not `edgedb dump`), the goal is to export data out of EgdeDB into a plain postgres instance. In such cases, user probably does not want to have tables `"net::http"."ScheduledRequest"` and `"cfg"."Auth"` created.

**Review by aljazerzen — APPROVED** [review]

**Comment by scotttrinh** [comment]
@aljazerzen 

> That's because when using pg_dump (not edgedb dump), the goal is to export data out of EgdeDB into a plain postgres instance.

That's helpful context, thanks! I think once we have write SQL, we might want to support writing to this table and reading from it from Postgres, but maybe that's a separate concern than dumping. Thanks for the explanation!

**Pull request merged**
