### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by MiroslavPetrik**

### CODE REVIEW

**Comment by 1st1** [comment]
This one looks suspicious @colinhacks

**Comment by 1st1** [comment]
> This one looks suspicious @colinhacks

Oh, sorry, it's legit. This is from the current code:

>  Parameter <json>$data: {"name":"Fido", "legs": 4}

Why are we suddenly switching to animal schema from the User/Movies schema we use everywhere else?

**Comment by colinhacks** [comment]
Hm not sure. I'll switch to the `Movie` schema in the `getting-started` PR.

**Comment by colinhacks** [comment]
Closing this in favor of https://github.com/edgedb/edgedb/pull/4275 But good catch @MiroslavPetrik!

**Pull request closed without merging**
