### PR TITLE
Add functions to manipulate sequence state and preserve sequence state in dumps

### PR DESCRIPTION
**Pull request by elprans**
### Implement functions to explicitly advance or reset a sequence value

The new `std::sequence_next(schema::ScalarType)` function
returns the next value for the specified sequence type.

The new `std::sequence_reset(schema::ScalarType, std::int64)`
function sets the _current_ value of the specified sequence, the
next call to `sequence_next` will return the next value in sequence.

The new `std::sequence_reset(schema::ScalarType)`
function resets the specified sequence to its initial state, so
the next call to `sequence_next` will return the start value of the
sequence.

### Make sure sequence state gets included in dumps

The current value of a sequence type is a piece of data that must be
preserved in the database dump.

Fixes: #2441

### CODE REVIEW

**Comment by 1st1** [comment]
> The new std::sequence_set_cur_value(schema::ScalarType, std::int64)
function sets the current value of the specified sequence.

Given that we have `datetime_current()` I wouldn't use the `cur` here and just spell it out in full. The name is already long. That said, I would omit "value" -- it's not needed here -- so it would be:

`std::sequence_get_next()`
`std::sequence_set_next()`
`std::sequence_set_current()`

But then I don't like the `get_next()` function because it's not clear if it's advancing the internal sequence counter or not. So I'd call it `std::sequence_advance()` or just `std::sequence_next()`

Lastly, do we really need `std::sequence_set_current()` *and* `std::sequence_set_next()`? Can we have just one function?

**Comment by elprans** [comment]
> Lastly, do we really need `std::sequence_set_current()` _and_ `std::sequence_set_next()`? Can we have just one function?

Then it would have to be `set_current()`, because that is needed in dumps.  Postgres has both variants, albeit as an argument to `nextval()`, and `set_next()` semantics is the default behavior.

> call it `std::sequence_advance()` just `std::sequence_next()`

I considered these.  `advance()` doesn't make it clear that it returns the value and isn't very discoverable, and `next()` is a bit too close to `set_next()`, but I can live with that, I think.

**Comment by 1st1** [comment]
So I'd go with two for now: `std::sequence_next()` and `std::sequence_set_current()`.

**Comment by elprans** [comment]
Actually, the use case for `set_next()` is to be able to reset the sequence back to the initial value.  If we only have `set_current()`, there will be no way to generate a value of `1`.

**Comment by 1st1** [comment]
I'd be fine with `std::sequence_next()`, `std::sequence_set_current()`, and `std::sequence_set_next()`.

**Review by 1st1 — COMMENTED** [review]
Can you please add some docs too? They don't have to be elaborate at this point.

**Comment by elprans** [comment]
Renamed.

**Review by 1st1 — APPROVED** [review]
LGTM, but please add some docs!

**Comment by elprans** [comment]
Docs added.

**Review by msullivan — APPROVED** [review]
Seems good, though the current/next distinction is kind of a shame

**Comment by tailhook** [comment]
> Actually, the use case for set_next() is to be able to reset the sequence back to the initial value. If we only have set_current(), there will be no way to generate a value of 1.

Can we have `sequence_set_current(type, val)` and `sequence_reset(type)` instead ?

**Comment by elprans** [comment]
> Can we have `sequence_set_current(type, val)` and `sequence_reset(type)` instead ?

We could, but I'm concerned we could miss some other important use case for setting the next value of the sequence exactly.

Another option is to do what Postgres does and use a single function with a kwarg:

```
sequence_set(type, val, NAMED ONLY used)
```

Where `used` would determine if `val` should be considered the current or next value.  I think multiple functions is clearer, though.

**Comment by 1st1** [comment]
We've decided to have one function with two variants:

* std::sequence_reset(type) -- reset to initial value
* std::sequence_reset(type, value) -- reset the current value to the supplied one

**Comment by elprans** [comment]
Changed to `sequence_reset`

**Pull request merged**
